repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff - format
        description: "format files"
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
      - id: ruff-check
        name: ruff - check
        description: "linting files"
        language: system
        entry: ruff check --fix
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
      - id: mypy
        name: mypy
        description: "static checks"
        language: system
        entry: mypy
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
