repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff - format
        description: "Run 'ruff' to format files"
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
